name: Delete Deployment
on:
  delete:
    branches:
  workflow_dispatch: # Allow manual trigger
  inputs:
    environment:
      description: 'Target environment for deletion'
      required: true
      default: 'production'
jobs:
  app:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    steps:
      - uses: codingjoe/the-box/actions/delete@main
        with:
          ssh-host: ${{ vars.SSH_HOSTNAME }}
          ssh-known-hosts: ${{ vars.SSH_KNOWN_HOSTS }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          hostname: ${{ case(github.ref == 'refs/heads/main', vars.HOSTNAME, format('{0}.{1}', github.event.ref_name, vars.HOSTNAME)) }}
          dotenv-private-key: ${{ secrets.DOTENV_PRIVATE_KEY_PRODUCTION }}
          environment: ${{ job.environment.name }}
