name: Deploy
on:
  workflow_run:
    workflows: [ci]
    strategy: wait-all
    timeout: 0
    branches: [main]
    types:
      - completed
  workflow_dispatch: # Allow manual trigger
    inputs:
      environment:
        description: 'Target environment for deployment'
        required: true
        default: 'production'
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false
jobs:
  app:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environment || 'production' }}
      url: https://${{ case(github.ref == 'refs/heads/main', vars.HOSTNAME, format('{0}.{1}', github.event.ref_name, vars.HOSTNAME)) }}
    steps:
      - run: echo "${{ job.environment.name }}"
      - uses: codingjoe/the-box/actions/deploy@main
        with:
          ssh-host: ${{ vars.SSH_HOSTNAME }}
          ssh-known-hosts: ${{ vars.SSH_KNOWN_HOSTS }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          hostname: ${{ case(github.ref == 'refs/heads/main', vars.HOSTNAME, format('{0}.{1}', github.event.ref_name, vars.HOSTNAME)) }}
          dotenv-private-key: ${{ secrets.DOTENV_PRIVATE_KEY_PRODUCTION }}
