name: Deploy
on:
  workflow_run:
    workflows: [ci]
    strategy: wait-all
    timeout: 0
    branches: [main]
    types:
      - completed
  workflow_dispatch: # Allow manual trigger
    inputs:
      environment:
        description: 'Target environment for deployment'
        required: true
        default: 'production'
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: false
jobs:
  app:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'production' }}
    steps:
      - uses: codingjoe/the-box/actions/deploy@main
        with:
          ssh-host: ${{ vars.SSH_HOSTNAME }}
          ssh-known-hosts: ${{ vars.SSH_KNOWN_HOSTS }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          hostname: ${{ vars.HOSTNAME }}
          dotenv-private-key: ${{ secrets.DOTENV_PRIVATE_KEY_PRODUCTION }}
          project-name: ${{ github.event.inputs.environment || 'production' }}
          file: compose.app.yml
