name: 📦 | Update The Box
on:
  schedule:
    - cron: '0 4 * * *' # Run daily at 4:00 AM UTC
  workflow_dispatch: # Allow manual trigger
concurrency:
  group: the-box-update
  cancel-in-progress: false
jobs:
  update:
    name: Update The Box
    runs-on: ubuntu-latest
    steps:
      - uses: codingjoe/the-box/actions/update@main
        with:
          ssh-host: ${{ vars.SSH_HOSTNAME }}
          ssh-known-hosts: ${{ vars.SSH_KNOWN_HOSTS }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
